### ISSUE TITLE
Provide error message when VIN doesn't have an update

### ISSUE THREAD

**Issue by Caellian** [zeld/psa-update#8]
Hi, the `‎DEVICE_URL` returns 404 if there's no updates for provided VIN, and 400 if it's invalid.
In case there's no updates, the program just closes without any feedback.

**Comment by zeld** [comment]
Hi,

Thanks for the feedback. I'm a bit surprised as the device API is meant to return information about the infotainment system in the car (NAC, RCC), whether there is an update or not.

To me 404 would mean that the VIN was not found, because it is not known in Stellantis database. For example when it is not a Stellantis car. Also when hitting a 404 on the device API, the program should fail with "Device not found, make sure the VIN {} is correct".

What I suspect is that maybe the getAvailableUpdate API returns OK but with an empty list of updates. I will investigate it a bit more and try to do some tests.

**Comment by Caellian** [comment]
For reference, it's Citroen C4 2016 VIN. Not sure if VIN is sensitive info so I'm not sharing that.

It's correctly formatted, as incorrect VIN returned 400.

**Comment by zeld** [comment]
I did some testing and investigated where the program would stop without any feedback but could not find anything so far.

Are you using latest version 1.0.4 (run psa-update --version)?
Are you executing the program from a terminal or just double clicking on it?
Are you running in interactive or silent mode?

**Comment by Caellian** [comment]
> Are you using latest version 1.0.4 (run psa-update --version)?
> Are you executing the program from a terminal or just double clicking on it?
> Are you running in interactive or silent mode?

Can't answer any of those questions. I reported this issue on behalf of my sisters husband during conversation.
Tried running it myself from the terminal now with the same VIN, and I get error:
> Error: Device not found, make sure the VIN \*\*\*\*\* is correct.

I took a closer look at the sources and the error gets correctly handled (for 404), so I'm closing this as "can't reproduce". Sorry for wasting your time, it's likely he opened it by double-clicking at the time, and thanks for quick response.
